language: java
jdk: oraclejdk8
services: docker
script:
  - ./gradlew clean build jacocoTestReport coveralls

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t dawidkotarba/backend_test:latest .;
    docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD";
    docker push dawidkotarba/backend_test:latest;
    fi